/* ===================================================
   js/data.js — ARCHIVO EXCLUSIVO DE DATOS (MÓDULO)
=================================================== */

// 1. El gran objeto seguro con todas las traducciones de la web
export const elementosATraducir = {
  ES: {
    // Navbar
    "navbar.brandFirstName": "SEBASTIÁN",
    "navbar.brandLastName": "ZAMPERONI",
    "navbar.language": "EN",
    "navbar.home": "Inicio",
    "navbar.about": "Sobre mí",
    "navbar.plans": "Planes",
    "navbar.testimonials": "Opiniones",
    "navbar.contact": "Contacto",
    "navbar.startNow": "Empezá ahora",
    
    // Hero
    "hero.disciplines.swimming": "NATACIÓN",
    "hero.disciplines.running": "RUNNING",
    "hero.disciplines.cycling": "CICLISMO",
    "hero.disciplines.triathlon": "TRIATLÓN",
    "hero.seoTitle": "SEBASTIÁN ZAMPERONI — ENTRENADOR DE TRIATLÓN, RUNNING Y NATACIÓN EN BUENOS AIRES",
    "hero.visualTitleLineOne": "ENTRENAMIENTO REAL",
    "hero.visualTitleEmphasisLineOne": "PARA DESAFÍOS",
    "hero.visualTitleEmphasisLineTwo": "EXTRAORDINARIOS.",
    "hero.subtitleLineOne": "Preparación en natación, running, ciclismo y triatlón",
    "hero.subtitleLineTwo": "de la mano de un entrenador que entiende tus tiempos.",
    "hero.teamName": "TRIA TEAM",
    "hero.viewPlans": "VER PLANES",
    "hero.meetCoach": "CONOCER AL ENTRENADOR",
    "hero.stats.athletesValue": "+200",
    "hero.stats.athletesLabel": "ATLETAS ENTRENADOS",
    "hero.stats.finishesValue": "+30",
    "hero.stats.finishesLabel": "FINISHES LARGA DISTANCIA",
    "hero.stats.experienceValue": "+32 años",
    "hero.stats.experienceLabel": "DE EXPERIENCIA",

    // Sobre Mí
    "about.eyebrow": "SOBRE MÍ",
    "about.titleLineOne": "UN ENTRENADOR QUE",
    "about.titleEmphasis": "COMPITE Y ENTIENDE.",
    "about.imageTag.name": "Sebastián Zamperoni",
    "about.imageTag.role": "PROFESOR Y ENTRENADOR · SZ TRIA TEAM",
    "about.credentials.certified.title": "Entrenador certificado",
    "about.credentials.certified.description": "Especialización en deportes de resistencia",
    "about.credentials.finishes.title": "+30 finishes en larga distancia",
    "about.credentials.finishes.description": "Atleta activo en competencias nacionales e internacionales",
    "about.credentials.athletes.title": "+200 atletas entrenados",
    "about.credentials.athletes.description": "Desde principiantes hasta competidores de élite amateur",
    "about.credentials.trainingPeaks.title": "Gestión y monitoreo en TrainingPeaks",
    "about.credentials.trainingPeaks.description": "Plataforma líder en planificación de resistencia",
    "about.paragraphOne": "Soy Sebastián Zamperoni, profesor y entrenador certificado con más de 32 años dedicados al deporte de resistencia. No solo entreno atletas — compito con ellos. Eso me da una perspectiva real que va más allá de la teoría.",
    "about.paragraphTwo": "A lo largo de mi carrera como entrenador y atleta, participé en innumerables triatlones de todas las distancias, tanto nacionales como internacionales, logrando podios y posiciones en el top ten de las clasificaciones generales. Completé finishes en distancias largas, corrí maratones y dominé aguas abiertas. Sé lo que se siente llegar al kilómetro 35 con las piernas vacías, y también sé exactamente cómo evitarlo.",
    "about.paragraphThree": "Mi método combina planificación basada en datos con acompañamiento humano real. Cada atleta tiene tiempos, contextos y objetivos distintos — mis planes se adaptan a eso, no al revés.",
    "about.paragraphThree": "Mi método combina planificación basada en datos con acompañamiento humano real. Cada atleta tiene tiempos, contextos y objetivos distintos — mis planes se adaptan a eso, no al revés.",
    "about.viewPlans": "VER MIS PLANES",
    
    // === ESTAS 4 LÍNEAS FALTABAN EN ESPAÑOL ===
    "about.disciplines.swimming": "Natación",
    "about.disciplines.running": "Running",
    "about.disciplines.cycling": "Ciclismo",
    "about.disciplines.triathlon": "Triatlón",
    "about.viewPlans": "VER MIS PLANES",

    // Planes Cabecera
    "plans.eyebrow": "PROGRAMAS DE ENTRENAMIENTO",
    "plans.title": "PLANES PREMIUM",
    "plans.description": "Programas estructurados y personalizados, entregados por TrainingPeaks. Cada plan es una hoja de ruta completa hacia tu objetivo.",
    "plans.ctaQuestion": "¿No sabés cuál plan se adapta mejor a vos?",
    "plans.ctaButton": "CONSULTAME GRATIS",

    // Textos de las tarjetas de los Planes
// Textos globales y copetes de los Planes (NUEVO)
    "plan.global.integrated": "Plan Integrado con TrainingPeaks",
    "plan.natacion.tag": "Técnica · Resistencia · Aguas Abiertas",
    "plan.triatlon.tag": "Sprint · Short · 70.3 · Full Ironman",
    "plan.running.tag": "10K · Media Maratón · Maratón",

    // ... el resto de tus planes en español sigue igual abajo ...
    //bloque añadido ATENCIONNNNN 
    "plan.natacion.titulo": "Plan Técnico de<br />Natación",
    "plan.natacion.desc": "Diseñado para nadadores de pileta o atletas de aguas abiertas que buscan perfeccionar su brazada, mejorar su eficiencia hidrodinámica y ganar confianza en distancias largas.",
    "plan.natacion.f1": "Análisis biomecánico inicial de brazada",
    "plan.natacion.f2": "Entrenamientos estructurados de pileta y aguas abiertas",
    "plan.natacion.f3": "Optimización de ritmos críticos (CSS)",
    "plan.natacion.f4": "Monitoreo semanal mediante TrainingPeaks",
    "plan.natacion.btn": "Consultar",

    "plan.triatlon.titulo": "Preparación<br />Triatlón Integral",
    "plan.triatlon.desc": "El programa insignia. Planificación unificada de las 3 disciplinas adaptada a tu zona de potencia, umbrales y tiempos disponibles, maximizando la asimilación del estímulo.",
    "plan.triatlon.f1": "Natación, ciclismo y running integrados en un solo bloque",
    "plan.triatlon.f2": "Transiciones técnicas (T1/T2) y estrategia de carrera",
    "plan.triatlon.f3": "Gestión avanzada de carga acumulada (TSS)",
    "plan.triatlon.f4": "Soporte prioritario y análisis de rendimiento diario",
    "plan.triatlon.btn": "Empezá ahora",

    "plan.running.titulo": "Performance<br />Running Plan",
    "plan.running.desc": "Pensado para corredores que quieren colgarse su primera medalla o pulverizar sus marcas personales en distancias de calle o trail, estructurando pasadas, fondos y fuerza.",
    "plan.running.f1": "Periodización inteligente basada en tus umbrales de ritmo",
    "plan.running.f2": "Pasadas de pista, cuestas y fuerza específica",
    "plan.running.f3": "Estrategia de ritmos milimétrica para el día de la carrera",
    "plan.running.f4": "Análisis de datos de carrera en TrainingPeaks",
    "plan.running.btn": "Consultar",

    // TrainingPeaks Section
    "trainingPeaks.eyebrow": "PLATAFORMA OFICIAL",
    "trainingPeaks.titleLineOne": "ENTRENAMOS CON",
    "trainingPeaks.titleEmphasis": "TRAININGPEAKS",
    "trainingPeaks.description.prefix": "Todos mis planes se gestionan a través de",
    "trainingPeaks.description.brand": "TrainingPeaks",
    "trainingPeaks.description.suffix": ", la plataforma web y móvil líder mundial diseñada para que atletas y entrenadores planifiquen, analicen y sigan entrenamientos de resistencia.",
    "trainingPeaks.features.planning.title": "Planificación estructurada",
    "trainingPeaks.features.planning.description": "Tu plan semana a semana con cada sesión detallada: duración, zonas, métricas y objetivos.",
    "trainingPeaks.features.analysis.title": "Análisis de rendimiento",
    "trainingPeaks.features.analysis.description": "Métricas avanzadas de carga, TSS, CTL y ATL para entender tu progreso real.",
    "trainingPeaks.features.mobile.title": "App móvil siempre disponible",
    "trainingPeaks.features.mobile.description": "Accedé desde el celular y sincronizá con Garmin, Wahoo, Polar y más.",
    "trainingPeaks.features.feedback.title": "Feedback directo del entrenador",
    "trainingPeaks.features.feedback.description": "Comentá cada sesión y recibís retroalimentación personalizada.",
    "trainingPeaks.learnMore": "CONOCER TRAININGPEAKS",
    "trainingPeaks.dashboard.title": "TRAININGPEAKS · DASHBOARD",
    "trainingPeaks.dashboard.metrics.ctlLabel": "CTL (FORMA)",
    "trainingPeaks.dashboard.metrics.ctlValue": "82",
    "trainingPeaks.dashboard.metrics.atlLabel": "ATL (FATIGA)",
    "trainingPeaks.dashboard.metrics.atlValue": "94",
    "trainingPeaks.dashboard.metrics.tsbLabel": "TSB (ESTADO)",
    "trainingPeaks.dashboard.metrics.tsbValue": "−12",
    "trainingPeaks.dashboard.weeklyLoad": "CARGA SEMANAL — SEMANA 14",
    "trainingPeaks.dashboard.days.monday": "L",
    "trainingPeaks.dashboard.days.tuesday": "M",
    "trainingPeaks.dashboard.days.wednesday": "Mi",
    "trainingPeaks.dashboard.days.thursday": "J",
    "trainingPeaks.dashboard.days.friday": "V",
    "trainingPeaks.dashboard.days.saturday": "S",
    "trainingPeaks.dashboard.days.sunday": "D",
    "trainingPeaks.dashboard.today.title": "SESIÓN DE HOY",
    "trainingPeaks.dashboard.today.discipline": "NATACIÓN",
    "trainingPeaks.dashboard.today.description": "Técnica de brazada · 2.400m · Zona 2 · 65 min",
    "trainingPeaks.dashboard.today.completed": "44 min completados",
    "trainingPeaks.dashboard.today.progress": "68%",
    "trainingPeaks.integrations.garmin": "GARMIN",
    "trainingPeaks.integrations.wahoo": "WAHOO",
    "trainingPeaks.integrations.polar": "POLAR",
    "trainingPeaks.integrations.strava": "STRAVA",

    // Testimonios Cabecera
    "testimonials.eyebrow": "VOCES REALES",
    "testimonials.titleLineOne": "LO QUE DICEN",
    "testimonials.titleEmphasis": "MIS ATLETAS",
    "testimonials.description": "Resultados concretos, historias reales. Deslizá para ver más.",

    // Textos de los 7 Testimonios
    "testi.juan.disciplina": "Triatlón",
    "testi.juan.cita": "Llegué a Sebastián con más miedos e impedimentos psicológicos que no me dejaban pasar de nivel. Gracias a su paciencia, enseñanza y su forma de ser, hizo que yo desbloqueara mi cabeza y ya haya hecho 4 triatlones en 4 meses, y ahora apuntando a mucho más.",
    "testi.juan.logro": "Cuatro triatlones en cuatro meses",
    "testi.ximena.disciplina": "Triatlón 70.3 · Maratón",
    "testi.ximena.cita": "Vengo del hockey y empecé triatlón en diciembre de 2023. En pocos meses, Sebas logró ver en mí un potencial que yo todavía no podía imaginar. En abril de 2025 ya estaba cruzando la meta de mi primer Ironman 70.3 en San Juan. Más allá de su planificación profesional impecable, valoro muchísimo su capacidad para acompañar, motivar y sacar lo mejor de cada atleta.",
    "testi.ximena.logro": "Ironman 70.3 en San Juan",
    "testi.alan.disciplina": "Triatlón",
    "testi.alan.cita": "Nos conocemos desde hace 20 años... Yo dejé de entrenar estos últimos 8 años y, cuando quise volver, no dudé en hablarle. porqué sabía que iba a respetar un proceso acorde y que, además de ser un gran entrenador, es una excelente persona.",
    "testi.alan.logro": "Volvió al triatlón después de más de 10 años",
    "testi.nacho.disciplina": "Triatlón · 70.3",
    "testi.nacho.cita": "Sebastián está siempre pendiente del resultado de los entrenamientos; la consulta y el feedback son permanentes. El resultado es un programa que se adapta a tus necesidades y la seguridad de sentirte acompañado en el proceso.",
    "testi.nacho.logro": "Clasificación al Mundial de Niza 2026 - 2.º puesto en su categoría en el IRONMAN 70.3 Cap Cana",
    "testi.felipe.disciplina": "Triatlón · 70.3",
    "testi.felipe.cita": "Gran entrenador y gran persona. De manera súper responsable me llevó de la nada a completar dos 70.3 y tres olímpicos con pocos meses de entrenamiento. Los planes están buenos y, si hay alguna duda, Seba está siempre a mano respondiendo con toda su experiencia en deportes de resistencia.",
    "testi.felipe.logro": "Dos 70.3 y tres olímpicos con pocos meses de entrenamiento",
    "testi.cristian.disciplina": "Natación · Aguas abiertas",
    "testi.cristian.cita": "Mi nombre es Cristian Fernández, soy nadador de aguas abiertas y triatleta. [...] Entreno con Seba desde mediados de 2024 y, desde el principio, hubo muy buena comunicación y conexión. El trabajo que ha hecho Seba ha sido excelente; fui mejorando muchísimo con el correr del tiempo [...]. Siento que evolucioné muchísimo en todas las disciplinas, logrando bajar mis tiempos personales y obteniendo excelentes resultados. Hoy estoy preparando un gran reto: una travesía de 10 km de aguas abiertas [...] y también el gran objetivo del año: bajar las 5 horas en el Ironman 70.3 de Cozumel. ¡Muchas gracias, Seba! ¡Vamos por más!",
    "testi.cristian.logro": "Triatlón Olímpico - 3.º puesto Gral.",
    "testi.lucas.disciplina": "Triatlón · 70.3",
    "testi.lucas.cita": "Entreno con Seba desde hace varios años y siempre logré alcanzar mis objetivos en carreras de calle y triatlones, mejorando año a año los tiempos y sin lesiones. Más allá de su gran predisposición y la calidad de los planes, lo que realmente lo distingue es su interés genuino por la persona detrás del atleta, entendiendo los tiempos y motivaciones de cada alumno para sacar su mejor versión.",
    "testi.lucas.logro": "Finisher IRONMAN 70.3",

    // Contacto
    "contact.eyebrow": "HABLEMOS",
    "contact.titleLineOne": "TU PRÓXIMO",
    "contact.titleEmphasis": "DESAFÍO EMPIEZA ACÁ.",
    "contact.descriptionLineOne": "Completá el formulario y te respondo en menos de 24hs.",
    "contact.descriptionLineTwo": "La primera consulta es siempre gratuita.",
    "contact.details.location.label": "UBICACIÓN",
    "contact.details.location.value": "Ciudad de Buenos Aires, Argentina",
    "contact.details.whatsapp.label": "WHATSAPP",
    "contact.details.whatsapp.value": "+54 9 11 5746 3710",
    "contact.details.email.label": "EMAIL",
    "contact.details.email.value": "sebaszampe@gmail.com",
    "contact.details.instagram.label": "INSTAGRAM",
    "contact.details.instagram.value": "@sebastianzamperoni",
    "contact.form.title": "ENVIÁ TU CONSULTA",
    "contact.form.nameLabel": "NOMBRE",
    "contact.form.phoneLabel": "WHATSAPP / TELÉFONO",
    "contact.form.emailLabel": "EMAIL",
    "contact.form.goalLabel": "¿CUÁL ES TU PRÓXIMO OBJETIVO?",
    "contact.form.goalOptions.placeholder": "Seleccioná tu meta",
    "contact.form.goalOptions.swimming": "Plan Técnico de Natación / Aguas Abiertas",
    "contact.form.goalOptions.triathlon": "Preparación Triatlón Integral (Short / 70.3 / Ironman)",
    "contact.form.goalOptions.running": "Performance Running Plan (Calle / Trail)",
    "contact.form.goalOptions.other": "Otro objetivo / Consulta general",
    "contact.form.currentTrainingLabel": "¿ENTRENÁS ACTUALMENTE?",
    "contact.form.trainingOptions.yes": "Sí",
    "contact.form.trainingOptions.no": "No, quiero empezar",
    "contact.form.trainingOptions.irregular": "Irregular",
    "contact.form.commentLabel": "¿ALGO MÁS QUE QUIERAS CONTARME?",
    "contact.form.submit": "ENVIAR CONSULTA",
    "contact.form.reset": "LIMPIAR",

    // Footer
    "footer.brandFirstName": "SEBASTIÁN",
    "footer.brandLastName": "ZAMPERONI",
    "footer.descriptionLineOne": "Profesor y entrenador · SZ Tria Team",
    "footer.descriptionLineTwo": "Natación · Running · Ciclismo · Triatlón",
    "footer.trainingPeaksNote": "PLANES GESTIONADOS POR TRAININGPEAKS",
    "footer.navigation.title": "NAVEGACIÓN",
    "footer.navigation.home": "Inicio",
    "footer.navigation.about": "Sobre mí",
    "footer.navigation.plans": "Planes",
    "footer.navigation.trainingPeaks": "TrainingPeaks",
    "footer.navigation.testimonials": "Opiniones",
    "footer.navigation.contact": "Contacto",
    "footer.plans.title": "PLANES",
    "footer.plans.swimming": "Plan Técnico de Natación",
    "footer.plans.triathlon": "Preparación Triatlón Integral",
    "footer.plans.running": "Performance Running Plan",
    "footer.plans.freeConsultation": "Consulta gratuita",
    "footer.ctaQuestion": "¿LISTO PARA EL PRÓXIMO DESAFÍO?",
    "footer.ctaButton": "EMPEZÁ HOY",
    "footer.copyright": "© 2026 Sebastián Zamperoni · SZ Tria Team · Todos los derechos reservados",
    "footer.designedWithPrefix": "Diseñado con",
    "footer.designedWithSuffix": "para atletas que no se rinden x",
    "footer.designer": "LeaSpi",
// === TRADUCCIONES DE LA GALERÍA (ESPAÑOL) ===
    "galeria.caption.principal": "Mundial · 70.3",
    "galeria.caption.corredor": "Triatlón · T1",
    "galeria.caption.ciclismo": "70.3 · San Juan",
    "galeria.caption.pileta": "Alumnos · Pileta técnica",
    "galeria.caption.aguas": "Saliendo del agua · T1",
    "galeria.caption.plan": "Planificación",
    "galeria.caption.equipamiento": "Equipamiento · Técnica"  
},
  
  EN: {
    // Navbar
    "navbar.brandFirstName": "SEBASTIAN",
    "navbar.brandLastName": "ZAMPERONI",
    "navbar.language": "ES",
    "navbar.home": "Home",
    "navbar.about": "About Me",
    "navbar.plans": "Plans",
    "navbar.testimonials": "Testimonials",
    "navbar.contact": "Contact",
    "navbar.startNow": "Start Now",

    // Hero
    "hero.disciplines.swimming": "SWIMMING",
    "hero.disciplines.running": "RUNNING",
    "hero.disciplines.cycling": "CYCLING",
    "hero.disciplines.triathlon": "TRIATHLON",
    "hero.seoTitle": "SEBASTIAN ZAMPERONI — TRIATHLON, RUNNING AND SWIMMING COACH IN BUENOS AIRES",
    "hero.visualTitleLineOne": "REAL TRAINING",
    "hero.visualTitleEmphasisLineOne": "FOR EXTRAORDINARY",
    "hero.visualTitleEmphasisLineTwo": "CHALLENGES.",
    "hero.subtitleLineOne": "Preparation in swimming, running, cycling and triathlon",
    "hero.subtitleLineTwo": "by the hand of a coach who understands your schedule.",
    "hero.teamName": "TRIA TEAM",
    "hero.viewPlans": "VIEW PLANS",
    "hero.meetCoach": "MEET THE COACH",
    "hero.stats.athletesValue": "+200",
    "hero.stats.athletesLabel": "ATHLETES TRAINED",
    "hero.stats.finishesValue": "+30",
    "hero.stats.finishesLabel": "LONG DISTANCE FINISHES",
    "hero.stats.experienceValue": "+32 years",
    "hero.stats.experienceLabel": "OF EXPERIENCE",

    // Sobre Mí
    "about.eyebrow": "ABOUT ME",
    "about.titleLineOne": "A COACH WHO",
    "about.titleEmphasis": "COMPETES AND UNDERSTANDS.",
    "about.imageTag.name": "Sebastián Zamperoni",
    "about.imageTag.role": "PROFESSOR AND COACH · SZ TRIA TEAM",
    "about.credentials.certified.title": "Certified Coach",
    "about.credentials.certified.description": "Specialization in endurance sports",
    "about.credentials.finishes.title": "+30 long distance finishes",
    "about.credentials.finishes.description": "Active athlete in national and international competitions",
    "about.credentials.athletes.title": "+200 trained athletes",
    "about.credentials.athletes.description": "From beginners to elite amateur competitors",
    "about.credentials.trainingPeaks.title": "Management and monitoring on TrainingPeaks",
    "about.credentials.trainingPeaks.description": "Leading platform in endurance planning",
    "about.paragraphOne": "I am Sebastián Zamperoni, a certified professor and coach with more than 32 years dedicated to endurance sports. I don't just train athletes — I compete with them. That gives me a real perspective that goes beyond theory.",
    "about.paragraphTwo": "Throughout my career as a coach and athlete, I participated in countless triathlons of all distances, both national and international, achieving podiums and top ten positions in general classifications. I completed long distance finishes, ran marathons, and mastered open water. I know what it feels like to reach kilometer 35 with empty legs, and I also know exactly how to avoid it.",
    "about.paragraphThree": "My method combines data-driven planning with real human accompaniment. Each athlete has different times, contexts, and goals — my plans adapt to that, not the other way around.",
    "about.viewPlans": "VIEW MY PLANS",
        
    // === ESTAS 4 LÍNEAS FALTABAN EN INGLÉS ===
    "about.disciplines.swimming": "Swimming",
    "about.disciplines.running": "Running",
    "about.disciplines.cycling": "Cycling",
    "about.disciplines.triathlon": "Triathlon",

    // Planes Cabecera
    "plans.eyebrow": "TRAINING PROGRAMS",
    "plans.title": "PREMIUM PLANS",
    "plans.description": "Structured and personalized programs, delivered by TrainingPeaks. Each plan is a complete roadmap toward your goal.",
    "plans.ctaQuestion": "Don't know which plan fits you best?",
    "plans.ctaButton": "CONSULT ME FOR FREE",

    // Tarjetas de los Planes (Inglés)
// Textos globales y copetes de los Planes en Inglés (NUEVO)
    "plan.global.integrated": "Integrated Plan with TrainingPeaks",
    "plan.natacion.tag": "Technique · Endurance · Open Water",
    "plan.triatlon.tag": "Sprint · Short · 70.3 · Full Ironman",
    "plan.running.tag": "10K · Half Marathon · Marathon",
    //AÑADIDOS ATENCION----
    "plan.natacion.titulo": "Technical<br />Swimming Plan",
    "plan.natacion.desc": "Designed for pool swimmers or open water athletes looking to perfect their stroke, improve hydrodynamic efficiency, and gain confidence over long distances.",
    "plan.natacion.f1": "Initial biomechanical stroke analysis",
    "plan.natacion.f2": "Structured pool and open water workouts",
    "plan.natacion.f3": "Critical Swim Speed (CSS) optimization",
    "plan.natacion.f4": "Weekly monitoring via TrainingPeaks",
    "plan.natacion.btn": "Inquire",

    "plan.triatlon.titulo": "Comprehensive<br />Triathlon Prep",
    "plan.triatlon.desc": "The flagship program. Unified planning of all 3 disciplines adapted to your power zones, thresholds, and available time, maximizing training assimilation.",
    "plan.triatlon.f1": "Swimming, cycling, and running integrated into a single block",
    "plan.triatlon.f2": "Technical transitions (T1/T2) and race strategy",
    "plan.triatlon.f3": "Advanced training stress score (TSS) management",
    "plan.triatlon.f4": "Priority support and daily performance analysis",
    "plan.triatlon.btn": "Start now",

    "plan.running.titulo": "Performance<br />Running Plan",
    "plan.running.desc": "Designed for runners who want to grab their first medal or smash their personal bests in road or trail distances, structuring intervals, long runs, and strength.",
    "plan.running.f1": "Intelligent periodization based on your pace thresholds",
    "plan.running.f2": "Track intervals, hill repeats, and sport-specific strength",
    "plan.running.f3": "Milimetric pacing strategy for race day",
    "plan.running.f4": "Race data analysis on TrainingPeaks",
    "plan.running.btn": "Inquire",

    // TrainingPeaks Section
    "trainingPeaks.eyebrow": "OFFICIAL PLATFORM",
    "trainingPeaks.titleLineOne": "WE TRAIN WITH",
    "trainingPeaks.titleEmphasis": "TRAININGPEAKS",
    "trainingPeaks.description.prefix": "All my plans are managed through",
    "trainingPeaks.description.brand": "TrainingPeaks",
    "trainingPeaks.description.suffix": ", the world's leading web and mobile platform designed for athletes and coaches to plan, analyze and track endurance training.",
    "trainingPeaks.features.planning.title": "Structured planning",
    "trainingPeaks.features.planning.description": "Your week-by-week plan with every detailed session: duration, zones, metrics, and goals.",
    "trainingPeaks.features.analysis.title": "Performance analysis",
    "trainingPeaks.features.analysis.description": "Advanced metrics of load, TSS, CTL and ATL to understand your real progress.",
    "trainingPeaks.features.mobile.title": "Mobile app always available",
    "trainingPeaks.features.mobile.description": "Access from your cell phone and sync with Garmin, Wahoo, Polar and more.",
    "trainingPeaks.features.feedback.title": "Direct feedback from the coach",
    "trainingPeaks.features.feedback.description": "Comment on each session and receive personalized feedback.",
    "trainingPeaks.learnMore": "LEARN ABOUT TRAININGPEAKS",
    "trainingPeaks.dashboard.title": "TRAININGPEAKS · DASHBOARD",
    "trainingPeaks.dashboard.metrics.ctlLabel": "CTL (FITNESS)",
    "trainingPeaks.dashboard.metrics.ctlValue": "82",
    "trainingPeaks.dashboard.metrics.atlLabel": "ATL (FATIGUE)",
    "trainingPeaks.dashboard.metrics.atlValue": "94",
    "trainingPeaks.dashboard.metrics.tsbLabel": "TSB (FORM)",
    "trainingPeaks.dashboard.metrics.tsbValue": "−12",
    "trainingPeaks.dashboard.weeklyLoad": "WEEKLY LOAD — WEEK 14",
    "trainingPeaks.dashboard.days.monday": "M",
    "trainingPeaks.dashboard.days.tuesday": "T",
    "trainingPeaks.dashboard.days.wednesday": "W",
    "trainingPeaks.dashboard.days.thursday": "T",
    "trainingPeaks.dashboard.days.friday": "F",
    "trainingPeaks.dashboard.days.saturday": "S",
    "trainingPeaks.dashboard.days.sunday": "S",
    "trainingPeaks.dashboard.today.title": "TODAY'S SESSION",
    "trainingPeaks.dashboard.today.discipline": "SWIMMING",
    "trainingPeaks.dashboard.today.description": "Stroke technique · 2,400m · Zone 2 · 65 min",
    "trainingPeaks.dashboard.today.completed": "44 min completed",
    "trainingPeaks.dashboard.today.progress": "68%",
    "trainingPeaks.integrations.garmin": "GARMIN",
    "trainingPeaks.integrations.wahoo": "WAHOO",
    "trainingPeaks.integrations.polar": "POLAR",
    "trainingPeaks.integrations.strava": "STRAVA",

    // Testimonios Cabecera
    "testimonials.eyebrow": "REAL VOICES",
    "testimonials.titleLineOne": "WHAT THEY SAY",
    "testimonials.titleEmphasis": "MY ATHLETES",
    "testimonials.description": "Concrete results, real stories. Swipe to see more.",

    // Testimonios en Inglés
    "testi.juan.disciplina": "Triathlon",
    "testi.juan.cita": "I came to Sebastián with more fears and psychological impediments that wouldn't let me pass to the next level. Thanks to his patience, teaching and his way of being, he made me unlock my head and I have already done 4 triathlons in 4 months, and now aiming for much more.",
    "testi.juan.logro": "Four triathlons in four months",
    "testi.ximena.disciplina": "Triathlon 70.3 · Marathon",
    "testi.ximena.cita": "I come from hockey and started triathlon in December 2023. In a few months, Sebas managed to see a potential in me that I still couldn't imagine. In April 2025 I was already crossing the finish line of my first Ironman 70.3 in San Juan. Beyond his impeccable professional planning, I highly value his ability to accompany, motivate and bring out the best in each athlete.",
    "testi.ximena.logro": "Ironman 70.3 in San Juan",
    "testi.alan.disciplina": "Triathlon",
    "testi.alan.cita": "We have known each other for 20 years... I stopped training these last 8 years and, when I wanted to come back, I didn't hesitate to talk to him. Because I knew he would respect a process accordingly and that, besides being a great coach, he is an excellent person.",
    "testi.alan.logro": "Returned to triathlon after more than 10 years",
    "testi.nacho.disciplina": "Triathlon · 70.3",
    "testi.nacho.cita": "Sebastián is always aware of the result of the workouts; the consultation and feedback are permanent. The result is a program that adapts to your needs and the safety of feeling accompanied in the process.",
    "testi.nacho.logro": "Qualification for the World Championship Nice 2026 - 2nd place in his category at the IRONMAN 70.3 Cap Cana",
    "testi.felipe.disciplina": "Triathlon · 70.3",
    "testi.felipe.cita": "Great coach and great person. In a super responsible way he took me from nothing to completing two 70.3 and three olympics with a few months of training. The plans are good and, if there is any doubt, Seba is always at hand responding with all his experience in endurance sports.",
    "testi.felipe.logro": "Two 70.3 and three olympics with a few months of training",
    "testi.cristian.disciplina": "Swimming · Open water",
    "testi.cristian.cita": "My name is Cristian Fernández, I am an open water swimmer and triathlete. [...] I train with Seba since mid-2024 and, from the beginning, there was very good communication and connection. The work Seba has done has been excellent; I kept improving a lot over time [...]. I feel that I evolved a lot in all disciplines, managing to lower my personal times and obtaining excellent results. Today I am preparing a great challenge: a 10 km open water crossing [...] and also the big goal of the year: going under 5 hours at the Ironman 70.3 Cozumel. Thank you very much, Seba! Let's go for more!",
    "testi.cristian.logro": "Olympic Triathlon - 3rd place Overall",
    "testi.lucas.disciplina": "Triathlon · 70.3",
    "testi.lucas.cita": "I have been training with Seba for several years and I always managed to achieve my goals in street races and triathlons, improving times year after year and without injuries. Beyond his great predisposition and the quality of the plans, what really distinguishes him is his genuine interest in the person behind the athlete, understanding the times and motivations of each student to bring out their best version.",
    "testi.lucas.logro": "Finisher IRONMAN 70.3",

    // Contacto
    "contact.eyebrow": "LET'S TALK",
    "contact.titleLineOne": "YOUR NEXT",
    "contact.titleEmphasis": "CHALLENGE STARTS HERE.",
    "contact.descriptionLineOne": "Complete the form and I will respond in less than 24 hours.",
    "contact.descriptionLineTwo": "The first consultation is always free.",
    "contact.details.location.label": "LOCATION",
    "contact.details.location.value": "Buenos Aires City, Argentina",
    "contact.details.whatsapp.label": "WHATSAPP",
    "contact.details.whatsapp.value": "+54 9 11 5746 3710",
    "contact.details.email.label": "EMAIL",
    "contact.details.email.value": "sebaszampe@gmail.com",
    "contact.details.instagram.label": "INSTAGRAM",
    "contact.details.instagram.value": "@sebastianzamperoni",
    "contact.form.title": "SEND YOUR INQUIRY",
    "contact.form.nameLabel": "NAME",
    "contact.form.phoneLabel": "WHATSAPP / PHONE",
    "contact.form.emailLabel": "EMAIL",
    "contact.form.goalLabel": "WHAT IS YOUR NEXT GOAL?",
    "contact.form.goalOptions.placeholder": "Select your goal",
    "contact.form.goalOptions.swimming": "Swimming Technical Plan / Open Water",
    "contact.form.goalOptions.triathlon": "Comprehensive Triathlon Preparation (Short / 70.3 / Ironman)",
    "contact.form.goalOptions.running": "Performance Running Plan (Street / Trail)",
    "contact.form.goalOptions.other": "Other goal / General inquiry",
    "contact.form.currentTrainingLabel": "ARE YOU TRAINING CURRENTLY?",
    "contact.form.trainingOptions.yes": "Yes",
    "contact.form.trainingOptions.no": "No, I want to start",
    "contact.form.trainingOptions.irregular": "Irregular",
    "contact.form.commentLabel": "ANYTHING ELSE YOU WANT TO TELL ME?",
    "contact.form.submit": "SEND INQUIRY",
    "contact.form.reset": "CLEAR",

    // Footer
    "footer.brandFirstName": "SEBASTIAN",
    "footer.brandLastName": "ZAMPERONI",
    "footer.descriptionLineOne": "Professor and Coach · SZ Tria Team",
    "footer.descriptionLineTwo": "Swimming · Running · Cycling · Triathlon",
    "footer.trainingPeaksNote": "PLANS MANAGED BY TRAININGPEAKS",
    "footer.navigation.title": "NAVIGATION",
    "footer.navigation.home": "Home",
    "footer.navigation.about": "About me",
    "footer.navigation.plans": "Plans",
    "footer.navigation.trainingPeaks": "TrainingPeaks",
    "footer.navigation.testimonials": "Testimonials",
    "footer.navigation.contact": "Contact",
    "footer.plans.title": "PLANS",
    "footer.plans.swimming": "Swimming Technical Plan",
    "footer.plans.triathlon": "Comprehensive Triathlon Preparation",
    "footer.plans.running": "Performance Running Plan",
    "footer.plans.freeConsultation": "Free consultation",
    "footer.ctaQuestion": "READY FOR THE NEXT CHALLENGE?",
    "footer.ctaButton": "START TODAY",
    "footer.copyright": "© 2026 Sebastián Zamperoni · SZ Tria Team · All rights reserved",
    "footer.designedWithPrefix": "Designed with",
    "footer.designedWithSuffix": "for athletes who never give up x",
    "footer.designer": "LeaSpi",

    // === TRADUCCIONES DE LA GALERÍA (INGLÉS) ===
    "galeria.caption.principal": "World Championship · 70.3",
    "galeria.caption.corredor": "Triathlon · T1",
    "galeria.caption.ciclismo": "70.3 · San Juan",
    "galeria.caption.pileta": "Students · Technical Pool",
    "galeria.caption.aguas": "Exiting Water · T1",
    "galeria.caption.plan": "Planning",
    "galeria.caption.equipamiento": "Equipment · Technique"
  }
};

// 2. Estructuras físicas invariables para los Testimonios
export const testimoniosData = [
    { id: "juan", nombre: "Juan Fernando", avatar: "img/testimonios/juan_fernando.png", estrellas: 5, highlight: false },
    { id: "ximena", nombre: "Ximena", avatar: "img/testimonios/ximena.png", estrellas: 5, highlight: true },
    { id: "alan", nombre: "Alan", avatar: "img/testimonios/alan.png", estrellas: 5, highlight: false },
    { id: "nacho", nombre: "Nacho", avatar: "img/testimonios/nacho.png", estrellas: 5, highlight: false },
    { id: "felipe", nombre: "Felipe", avatar: "img/testimonios/felipe.png", estrellas: 5, highlight: false },
    { id: "cristian", nombre: "Cristian", avatar: "img/testimonios/cristian.png", estrellas: 5, highlight: true },
    { id: "lucas", nombre: "Lucas", avatar: "img/testimonios/lucas.png", estrellas: 5, highlight: true }
];

// 3. Estructuras físicas invariables para los Planes Premium
export const planesData = [
    { id: "svc-natacion", keyPrefix: "plan.natacion", iconClass: "bi-water", iconModifier: "", tag: "Técnica · Resistencia · Aguas Abiertas", highlight: false },
    { id: "svc-triatlon", keyPrefix: "plan.triatlon", iconClass: "bi-diagram-3", iconModifier: "svc-card__icon--gold", tag: "Sprint · Short · 70.3 · Full Ironman", highlight: true },
    { id: "svc-running", keyPrefix: "plan.running", iconClass: "bi-lightning-charge", iconModifier: "", tag: "10K · Media Maratón · Maratón", highlight: false }
];

// 4. Estructuras para la galería
export const galeriaData = [
    { id: "principal", src: "img/principal_m.png", alt: "Atleta cruzando la meta en triatlón", clase: "galeria__item--wide" },
    { id: "corredor", src: "img/galeria/corredor.png", alt: "Corredor en maratón", clase: "" },
    { id: "ciclismo", src: "img/galeria/ciclismo1.jpeg", alt: "Ciclista en carrera", clase: "" },
    { id: "pileta", src: "img/galeria/pileta.jpg", alt: "Nadadores en pileta", clase: "" },
    { id: "aguas", src: "img/galeria/aguas_abiertas.jpeg", alt: "Grupo nadando en lago", clase: "" },
    { id: "plan", src: "img/galeria/planificacion.jpg", alt: "Plan de entrenamiento", clase: "" },
    { id: "equipamiento", src: "img/galeria/equipamiento.jpg", alt: "Equipamiento de natación", clase: "" }
];